name: duration_format
description: A simple package to format a Duration object into a human-readable string.
version: 0.0.1
repository: https://github.com/Calebh101/duration_format

environment:
  sdk: ^3.5.4

dependencies:

dev_dependencies:
  lints: ^4.0.0
